version: "3.8"
services:
  # webhook
  ar-webhook:
    build:
      context: .
    image: ar-webhook
    container_name: ar-webhook
    env_file: "ar.env"
    depends_on:
      - ar-redis
    labels:
      - "anime-releases"
      - "anime-releases.webhook"

  # redis
  ar-redis:
    image: redis
    container_name: ar-redis
    labels:
      - "anime-releases"
      - "anime-releases.redis"
