version: "3.8"
services:
  # webhook
  ar-webhook:
    image: ghcr.io/sulaxan/anime-releases:latest
    container_name: ar-webhook
    env_file: "ar.env"
    depends_on:
      - ar-redis
    labels:
      - "anime-releases"
      - "anime-releases.webhook"

  # redis
  ar-redis:
    image: redis
    container_name: ar-redis
    labels:
      - "anime-releases"
      - "anime-releases.redis"
    volumes:
      - "/data/anime-releases/redis:/data"
