name: anime-releases-publish-image

on:
  push:
    branches:
      - master
      # support more branches in another file since there's master-specific logic in this workflow file

jobs:
  publish-image:
    name: Publish anime-releases image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: GitHub Container Registry login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com  # ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          context: ./webhook
          file: ./webhook/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: Sulaxan/anime-releases:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache

